//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorInformation
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor
    {
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string company { get; set; }
        public string visiting { get; set; }
        public string idtype { get; set; }
        public int Id { get; set; }
        public string vehicle { get; set; }
        public string contactnum { get; set; }
        public string visit { get; set; }
        public string visitorId { get; set; }
        public string status { get; set; }
        public System.DateTime checked_in { get; set; }
        public System.DateTime checked_out { get; set; }
    }
}
